# Generated by Django 3.1.1 on 2020-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
