# Generated by Django 3.1.1 on 2020-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_college_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
