# Generated by Django 3.1.1 on 2020-10-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20201006_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='femaleAcceptRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Acceptance rate for women'),
        ),
        migrations.AddField(
            model_name='college',
            name='femaleApps',
            field=models.IntegerField(default=0, verbose_name='female Applications'),
        ),
        migrations.AddField(
            model_name='college',
            name='maleAcceptRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Acceptance rate for men'),
        ),
        migrations.AddField(
            model_name='college',
            name='maleApps',
            field=models.IntegerField(default=0, verbose_name='Male Applications'),
        ),
        migrations.AddField(
            model_name='college',
            name='otherAcceptRate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Acceptance Rate for Other'),
        ),
        migrations.AddField(
            model_name='college',
            name='otherApps',
            field=models.IntegerField(blank=True, default=0, verbose_name='Other Applications'),
        ),
        migrations.AddField(
            model_name='college',
            name='totalApps',
            field=models.IntegerField(default=0, verbose_name='Total Applications'),
        ),
        migrations.AlterField(
            model_name='college',
            name='acceptRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Acceptance Rate'),
        ),
    ]
