# Generated by Django 3.1.1 on 2020-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20201008_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='acceptRate',
        ),
        migrations.RemoveField(
            model_name='college',
            name='femaleAcceptRate',
        ),
        migrations.RemoveField(
            model_name='college',
            name='maleAcceptRate',
        ),
        migrations.RemoveField(
            model_name='college',
            name='otherAcceptRate',
        ),
        migrations.AddField(
            model_name='college',
            name='femaleAdmits',
            field=models.IntegerField(default=0, verbose_name='Female Admissions'),
        ),
        migrations.AddField(
            model_name='college',
            name='maleAdmits',
            field=models.IntegerField(default=0, verbose_name='Male Admissions'),
        ),
        migrations.AddField(
            model_name='college',
            name='otherAdmits',
            field=models.IntegerField(blank=True, default=0, verbose_name='Other Admits'),
        ),
        migrations.AddField(
            model_name='college',
            name='totalAdmits',
            field=models.IntegerField(default=0, verbose_name='Total Admissions'),
        ),
    ]
