# Generated by Django 3.1.1 on 2020-10-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_auto_20201008_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='totalAdmits',
        ),
        migrations.RemoveField(
            model_name='college',
            name='totalApps',
        ),
    ]
