# Generated by Django 3.1.1 on 2020-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20201008_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='year',
            field=models.CharField(default='', max_length=9),
        ),
    ]
