# Generated by Django 3.1.1 on 2020-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_auto_20201008_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='actMath25th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='actMath75th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='actWriting25th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='actWriting75th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='admittedWaitlist',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='athConference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='athDiv',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='blackStudents',
            field=models.IntegerField(default=0, verbose_name='African American, non-hispanic Students'),
        ),
        migrations.AddField(
            model_name='college',
            name='hispanicStudents',
            field=models.IntegerField(default=0, verbose_name='Hispanic Students'),
        ),
        migrations.AddField(
            model_name='college',
            name='internationalStudents',
            field=models.IntegerField(default=0, verbose_name='International Students'),
        ),
        migrations.AddField(
            model_name='college',
            name='mixedStudents',
            field=models.IntegerField(default=0, verbose_name='Two or More races, non-hispanic'),
        ),
        migrations.AddField(
            model_name='college',
            name='nativeStudents',
            field=models.IntegerField(default=0, verbose_name='American Indian or Alaska Native, non-hispanic'),
        ),
        migrations.AddField(
            model_name='college',
            name='offeredWaitlist',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='satMath25th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='satMath75th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='satWriting25th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='satWriting75th',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='tookWaitlist',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='unknownStudents',
            field=models.IntegerField(default=0, verbose_name='unknown ethinicity'),
        ),
        migrations.AddField(
            model_name='college',
            name='whiteStudents',
            field=models.IntegerField(default=0, verbose_name='white, non-hispanic students'),
        ),
    ]
