# Generated by Django 3.1.1 on 2020-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20201012_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='asianStudents',
            field=models.IntegerField(default=0, verbose_name='Asian, non-hispanic'),
        ),
        migrations.AddField(
            model_name='college',
            name='pacificStudents',
            field=models.IntegerField(default=0, verbose_name='Native Hawaiian or Pacific Islander, non-hispanic'),
        ),
        migrations.AlterField(
            model_name='college',
            name='whiteStudents',
            field=models.IntegerField(default=0, verbose_name='Nhite, non-hispanic students'),
        ),
    ]
