# Generated by Django 3.1.1 on 2020-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20201012_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='boardCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='requiredFeeCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='roomCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='tuitionCost',
            field=models.IntegerField(default=0),
        ),
    ]
