# Generated by Django 3.1.1 on 2020-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_auto_20201021_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='studentFacultyRatio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
