# Generated by Django 3.1.1 on 2020-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0012_college_studentfacultyratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
