# Generated by Django 3.1.1 on 2020-10-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_college_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='actWriting25th',
            new_name='actEnglish25th',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='actWriting75th',
            new_name='actEnglish75th',
        ),
    ]
