# Generated by Django 3.1.1 on 2020-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0014_auto_20201029_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='otherAdmits',
        ),
        migrations.RemoveField(
            model_name='college',
            name='otherApps',
        ),
        migrations.AlterField(
            model_name='college',
            name='actEnglish25th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='actEnglish75th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='actMath25th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='actMath75th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='satMath25th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='satMath75th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='satWriting25th',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='satWriting75th',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
