# Generated by Django 3.1.1 on 2020-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0015_auto_20201029_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='inStateTuitionCost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
