# Generated by Django 3.1.1 on 2020-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0016_college_instatetuitioncost'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='gpaFour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='gpaThreeFive',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='gpaThreeSevenFive',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
