# Generated by Django 3.1.1 on 2020-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_auto_20201126_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='gpaFour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='college',
            name='gpaThreeFive',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='college',
            name='gpaThreeSevenFive',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
