# Generated by Django 3.1.3 on 2020-12-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_auto_20201126_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='avgFinAid',
            field=models.IntegerField(default=0),
        ),
    ]
